name: Bump version on call
on:
  workflow_call:
    inputs:
      bump_type:
        required: true
        type: string

jobs: 
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install bump2version
        run: pip install bump2version
      - name: Bump version
        run: bump2version --list ${{ inputs.bump_type }}