name: Bump version on call
on:
  workflow_call:
    inputs:
      bump_type:
        required: true
        type: string
      extra_branch:
        required: false
        type: string

jobs: 
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install bump2version
        run: pip install bump2version
      - name: Bump version
        run: bump2version ${{ inputs.bump_type }}
      - name: Push changes
        run: |
          git push --follow-tags

  update-extra-branch:
    needs: bump-version
    if: ${{ inputs.extra_branch != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current branch
        id: get_branch
        run: |
          echo "current_branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Cherry-pick to extra branch
        run: |
          git fetch --all
          git checkout ${{ inputs.extra_branch }}
          git cherry-pick ${{ env.current_branch }}
          git push origin ${{ inputs.extra_branch }}