name: CI for versioning

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:
  bump-patch:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'bump:patch') }}
    secrets: inherit
    uses: SBouchard01/test_ci/.github/workflows/bump-version.yml@main
    permissions:
      pull-requests: read
      contents: write
    with:
      bump_type: patch
  bump-minor:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'bump:minor') }}
    secrets: inherit
    uses: SBouchard01/test_ci/.github/workflows/bump-version.yml@main
    permissions:
      pull-requests: read
      contents: write
    with:
      bump_type: minor
  bump-major:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'bump:major') }}
    secrets: inherit
    uses: SBouchard01/test_ci/.github/workflows/bump-version.yml@main
    permissions:
      pull-requests: read
      contents: write
    with:
      bump_type: major

  
  merge-dev: # Merge back main to dev to ensure the version change is propagated back to the dev branch
    needs: [bump-patch, bump-minor, bump-major] 
    # Run only if any of the bump jobs were triggered, regardless of their success or failure
    if: |
      always() && (
        needs.bump-patch.result == 'success' ||
        needs.bump-minor.result == 'success' ||
        needs.bump-major.result == 'success'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Merge main back into dev
        run: |
          git checkout dev
          git merge main --no-ff -m "Merge main into dev after version bump"
          git push origin dev